### ISSUE TITLE
How to set a proxy

### ISSUE THREAD

**Issue by albertotn** [zhicwu/docker-pdi-ce#31]
During step 5/12, following command is executed:

> Step 5/12 : RUN apt-get update  && apt-get clean        && rm -rf /var/lib/apt/lists/*  && useradd -md $KETTLE_HOME -s /bin/bash $PDI_USER

I'm trying to use this docker image inside a network with a proxy, so apt-get update will receive error. there is a way to specify proxy ?

**Comment by jaymz1439** [comment]
add the env http_proxy="" in the Dockerfile directly
